import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                "resources/css/app.css",
                "resources/css/universal_customer.css",
                "resources/css/universal_owner.css",
                "resources/css/page_parts/navbar.css",
                "resources/css/page_parts/footer.css",
                "resources/css/customer/signup.css",
                "resources/css/customer/login.css",
                "resources/css/customer/account.css",
                "resources/css/customer/edit_profile.css",
                "resources/css/customer/change_password.css",
                "resources/css/customer/reset_password.css",
                "resources/css/customer/enter_code.css",
                "resources/css/customer/new_password.css",
                "resources/css/customer/view_orders.css",
                "resources/css/customer/popups/tnc.css",
                "resources/css/customer/pages/aboutus.css",
                "resources/css/customer/pages/faqs.css",
                "resources/css/customer/pages/products.css",
                "resources/css/customer/pages/home.css",
                "resources/css/customer/pages/home_images.css",
                "resources/css/customer/pages/product_sample_modal.css",
                "resources/css/customer/pages/rush_fees.css",
                "resources/css/customer/pages/product-detail.css",
                "resources/css/customer/pages/order_modal.css",
                "resources/css/owner/parts/sidenav.css",
                "resources/css/owner/login.css",
                "resources/css/owner/pages/content_management/content_management.css",
                "resources/css/owner/pages/content_management/home_page_content.css",
                "resources/css/owner/pages/content_management/products_page_content.css",
                "resources/css/owner/pages/content_management/order_template.css",
                "resources/css/owner/pages/content_management/manage_categories.css",
                "resources/css/owner/pages/content_management/faq_management.css",
                "resources/css/owner/pages/dashboard.css",
                "resources/css/owner/pages/inventory.css",
                "resources/css/owner/pages/orders.css",
                "resources/js/app.js",
                "resources/js/tnc.js",
                "resources/js/customeraccount_options.js",
                "resources/js/owner/sidebar_account.js",
                "resources/js/customer/new_password.js",
                "resources/js/change_password_validation.js",
                "resources/js/edit_profile_validation.js",
                "resources/js/signup_validation.js",
                "resources/js/customer/pages/faqs_dynamic.js",
                "resources/js/customer/pages/login.js",
                "resources/js/customer/pages/products_page.js",
                "resources/js/customer/pages/product_sample_modal.js",
                "resources/js/customer/pages/home_product_samples.js",
                "resources/js/customer/pages/home_images_slideshow.js",
                "resources/js/customer/pages/rush_fees_display.js",
                "resources/js/customer/pages/product-detail.js",
                "resources/js/customer/pages/order_modal.js",
                "resources/js/customer/pages/view_orders.js",
                "resources/js/owner/animations.js",
                "resources/js/owner/inventory_refactored.js",
                "resources/js/owner/pages/orders.js",
                "resources/js/owner/content_page/main_content_page.js",
                "resources/js/owner/content_page/products_page_content_refactored.js",
                "resources/js/owner/content_page/edit_home_images_modal.js",
                "resources/js/owner/content_page/product_sample_modal.js",
                "resources/js/owner/content_page/order_template.js",
                "resources/js/owner/content_page/rush_fees.js",
                "resources/js/owner/content_page/manage_categories_modal.js",
                "resources/js/owner/content_page/faq_management.js",
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ["**/storage/framework/views/**"],
        },
        proxy: {
            "/api": {
                target: "http://127.0.0.1:8000",
                changeOrigin: true,
            },
            "/storage": {
                target: "http://127.0.0.1:8000",
                changeOrigin: true,
            },
        },
    },
});
